### ISSUE TITLE
Source code fails to compile

### ISSUE THREAD

**Issue by ericjohannsen** [GeorgeSchiro/GetCert#3]
Error	CS0103	The name 'SslFlags' does not exist in the current context	GetCert	E:\Dev\GetCert\GetCertClient\DoGetCert.cs	1651	Active

**Comment by GeorgeSchiro** [comment]
This is not an issue. Please read the requirements:

[GetCert Requirements](https://github.com/GeorgeSchiro/GetCert#Requirements)

Read also issue #1.

**Comment by ericjohannsen** [comment]
So you have to _compile_ on a Windows Server platform? I don't actually have VS installed on my servers and don't plan to, so I suppose I can't use this solution.

**Comment by GeorgeSchiro** [comment]
Yes, an important part of this solution is automated website creation (one per SAN). Having several sites on the same server using the same cert requires SNI support which in turn requires the version of "Microsoft.Web.Administration.dll" that runs on Win2012 and later.

That said, you can still use the solution since the EXE has been included.

**Comment by ericjohannsen** [comment]
The solution of running an EXE doesn't work for me as I review and compile from source any program not from a well-known vendor.

Unless I'm missing something, the only compilation issue is that the enum isn't defined on desktop versions of Windows. It may be worth considering replacing that enum with the documented value (1) or adding a comment in the code that those compiling on non-SNI versions of windows can make that substitution themselves. 

I believe it will still run correctly on Windows Server if compiled that way?

**Comment by GeorgeSchiro** [comment]
I fully understand not wanting to run an EXE from someone you don't know. I feel the same way. That's why I always test new stuff in VMs that can be discarded when done.

Please make whatever adjustments to the code that makes sense for you. I would be very interested in knowing what you come up with. Let me know also if you have any other questions. Thank you for your interest Eric.

**Comment by GeorgeSchiro** [comment]
Thank you for kicking me in the pants Eric. Please try again.
